{
 "title": "IoT Sensor Data",
 "tags": [ "iot" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "iot_sensor_temp" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "iot_sensor_hum" }
   ]
  },
  {
   "title": "PM1 (ug/m3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "iot_sensor_pm1" }
   ]
  },
  {
   "title": "PM2.5 (ug/m3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "iot_sensor_pm25" }
   ]
  },
  {
   "title": "PM10 (ug/m3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "iot_sensor_pm10" }
   ]
  },
  {
   "title": "Messages per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "count(iot_sensor_ts)" }
   ]
  }
 ]
}