apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emqx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://repos.emqx.io/charts
    targetRevision: 5.8.0
    chart: emqx
  destination:
    server: https://kubernetes.default.svc
    namespace: emqx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
