apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emqx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://www.emqx.io/downloads/emqx
    targetRevision: v5.8.0
    chart: emqx
    helm:
      releaseName: emqx
      valuesFiles:
        - ../../files/emqx-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: emqx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
