apiVersion: v1
kind: Pod
metadata:
  name: benthos
  namespace: benthos
spec:
  nodeName: raspberrypi
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: benthos
      image: jeffail/benthos:4.1.0
      ports:
        - containerPort: 4195
          hostPort: 4195
          name: http
      volumeMounts:
        - name: config
          mountPath: /benthos.yaml
          subPath: benthos.yaml
      livenessProbe:
        httpGet:
          path: /ping
          port: 4195
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 4195
        initialDelaySeconds: 10
        periodSeconds: 5
      resources:
        requests:
          cpu: "1500m"
          memory: 1Gi
        limits:
          cpu: "2000m"
          memory: 2Gi
  volumes:
    - name: config
      configMap:
        name: benthos-config
  tolerations:
    - key: "arm"
      operator: "Exists"
      effect: "NoSchedule"