---
- name: Install Kafka
  hosts: rpi-master1
  become: true
  vars:
    bitnami_repo_name: bitnami
    bitnami_repo_url: https://charts.bitnami.com/bitnami
  tasks:
    - name: Add Bitnami Helm repo
      community.kubernetes.helm_repository:
        name: "{{ bitnami_repo_name }}"
        repo_url: "{{ bitnami_repo_url }}"

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Kafka
      community.kubernetes.helm:
        name: kafka
        chart_ref: bitnami/kafka
        release_namespace: kafka
        create_namespace: true
        values_files:
          - files/kafka-values.yaml
