---
- name: Install Longhorn
  hosts: rpi-master1
  become: true
  vars:
    longhorn_repo_name: longhorn
    longhorn_repo_url: https://charts.longhorn.io
  tasks:
    - name: Add Longhorn Helm repo
      community.kubernetes.helm_repository:
        name: "{{ longhorn_repo_name }}"
        repo_url: "{{ longhorn_repo_url }}"

    - name: Update Helm repos
      shell: helm repo update

    - name: Install Longhorn
      community.kubernetes.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values_files:
          - files/longhorn-values.yaml

    - name: Apply custom StorageClass for Longhorn
      kubernetes.core.k8s:
        state: present
        src: files/longhorn-storageclass.yaml
