---
- name: Full reset Raspberry Pi nodes to barebones
  hosts: all
  become: true
  tasks:

    - name: Stop K3s service
      systemd:
        name: k3s
        state: stopped
        enabled: false
      ignore_errors: yes

    - name: Remove K3s
      shell: |
        /usr/local/bin/k3s-uninstall.sh || true
      ignore_errors: yes

    - name: Remove K3s systemd units
      file:
        path: /etc/systemd/system/k3s*
        state: absent
      ignore_errors: yes

    - name: Remove K3s directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/kubelet
        - /var/lib/cni
        - /var/lib/etcd
        - /run/k3s
      ignore_errors: yes

    - name: Remove Helm releases and charts
      shell: |
        helm ls -A -q | xargs -r helm uninstall -A
      ignore_errors: yes

    - name: Remove Kubernetes manifests and configs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/kubeadm
        - /var/run/kubernetes
      ignore_errors: yes

    - name: Remove container runtimes (Docker/Containerd)
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /var/lib/containerd
      ignore_errors: yes

    - name: Remove Longhorn data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/longhorn
        - /mnt/longhorn
      ignore_errors: yes

    - name: Remove MetalLB config
      file:
        path: /etc/metallb
        state: absent
      ignore_errors: yes

    - name: Clean remaining logs
      shell: |
        rm -rf /var/log/containers/*
        rm -rf /var/log/pods/*
      ignore_errors: yes
