"""The consumer has exactly one source of truth, and edits must reach the pods.

The script used to be embedded as a `data['consumer.py']` key inside a
hand-written `configmap.yaml`, with a second copy checked in beside it for
readability. Two failure modes, both observed rather than hypothetical:

  * the copies drifted, so the file people read and reviewed was not
    necessarily the file that ran;
  * editing `configmap.yaml` did not change the pod template, so `kubectl
    apply` printed "successfully rolled out" while every pod kept running the
    previous code. The bounded-retention fix was deployed that way and silently
    did nothing -- verified by the pods' age not changing across the apply.

The script is now a real file, `manifests/nats-consumer/consumer.py`, and
kustomize generates the ConfigMap from it. These tests pin the properties that
make that work.
"""

from __future__ import annotations

import ast
import shutil
import subprocess
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MANIFESTS = REPO / "manifests" / "nats-consumer"
CONSUMER = MANIFESTS / "consumer.py"
KUSTOMIZATION = MANIFESTS / "kustomization.yaml"


def render() -> tuple[int, str, str]:
    """Render the kustomization, if kustomize is available."""
    exe = shutil.which("kustomize")
    cmd = [exe, "build", str(MANIFESTS)] if exe else [
        "kubectl", "kustomize", str(MANIFESTS)
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    return res.returncode, res.stdout, res.stderr


class TestSingleSourceOfTruth(unittest.TestCase):
    def test_consumer_script_is_a_real_file(self):
        self.assertTrue(CONSUMER.is_file())

    def test_script_parses(self):
        ast.parse(CONSUMER.read_text())

    def test_no_hand_written_configmap_remains(self):
        """The old embedded-script ConfigMap must not come back."""
        self.assertFalse(
            (MANIFESTS / "configmap.yaml").exists(),
            "configmap.yaml is generated by kustomize now; a hand-written copy "
            "reintroduces the drift and the no-op rollout",
        )

    def test_kustomization_generates_the_configmap(self):
        k = KUSTOMIZATION.read_text()
        self.assertIn("configMapGenerator", k)
        self.assertIn("consumer.py", k)

    def test_kustomization_does_not_disable_the_hash(self):
        """Pinning the name removes the only thing that forces a rollout."""
        import yaml

        k = yaml.safe_load(KUSTOMIZATION.read_text())
        for gen in k.get("configMapGenerator", []):
            options = gen.get("options") or {}
            self.assertNotIn(
                "disableNameSuffixHash", options,
                "a pinned ConfigMap name means editing consumer.py cannot "
                "change the pod template, so the rollout is a no-op",
            )


@unittest.skipUnless(shutil.which("kubectl") or shutil.which("kustomize"),
                     "kustomize/kubectl not available")
class TestKustomizeRendersAndLinks(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.code, cls.out, cls.err = render()
        if cls.code != 0:
            raise unittest.SkipTest(f"kustomize build failed: {cls.err.strip()[:200]}")

    def test_renders(self):
        self.assertEqual(self.code, 0, self.err)
        self.assertIn("kind: ConfigMap", self.out)
        self.assertIn("kind: Deployment", self.out)

    def test_configmap_carries_the_script(self):
        self.assertIn("consumer.py: |", self.out)

    def test_configmap_name_is_content_hashed(self):
        """A stable name means an edit cannot reach the pods."""
        import re

        names = re.findall(r"^  name: (nats-consumer-script\S*)", self.out, re.M)
        self.assertTrue(names, "generated ConfigMap name not found")
        for name in names:
            self.assertNotEqual(
                name, "nats-consumer-script",
                "generated ConfigMap has no content-hash suffix, so editing "
                "consumer.py will not roll the pods",
            )

    def test_deployment_references_the_hashed_name(self):
        """The reference must be rewritten, or the pods mount nothing."""
        import re

        configmap_names = set(
            re.findall(r"^  name: (nats-consumer-script\S*)", self.out, re.M)
        )
        refs = set(re.findall(r"nats-consumer-script\S*", self.out.split("kind: Deployment", 1)[1]))
        self.assertTrue(refs, "Deployment has no ConfigMap reference")
        self.assertTrue(
            refs & configmap_names,
            f"Deployment references {refs} but the generated ConfigMap is "
            f"{configmap_names}; kustomize did not rewrite the volume",
        )

    def test_render_is_deterministic(self):
        code2, out2, _ = render()
        self.assertEqual(code2, 0)
        self.assertEqual(self.out, out2, "render is not deterministic")


class TestNoDuplicatedSeries(unittest.TestCase):
    """The ack pass must add series, not re-emit the payload.

    An earlier version of the two-pass write called the same renderer in both
    passes, so VictoriaMetrics held exactly twice as many samples of
    iot_sensor_ts and iot_sensor_nats_exit_ts as of latency_ms for the same
    messages: 55,720 against 27,860 in one 10c_1000r run. No error was raised,
    latency and throughput were unaffected, and it doubled the write volume.
    Only counting samples per series revealed it.
    """

    MESSAGE = {
        "device_id": "d1", "ts": 1000, "pm1": 1.5, "pm25": 2.5,
        "pm10": 3.0, "temp": 20.0, "hum": 40.0,
    }

    def _functions(self):
        tree = ast.parse(CONSUMER.read_text())
        ns = {}
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and node.name in (
                "format_metrics", "format_metrics_ack", "_render"
            ):
                exec(compile(ast.Module([node], []), "<f>", "exec"), ns)
        return ns

    @staticmethod
    def _names(lines):
        return {l.split("{")[0] for l in lines}

    def test_ack_pass_emits_no_payload_series(self):
        ns = self._functions()
        first = ns["format_metrics"](dict(self.MESSAGE), 1100)
        second = ns["format_metrics_ack"](dict(self.MESSAGE), 1250)
        self.assertEqual(self._names(first) & self._names(second), set())

    def test_ack_pass_emits_exactly_the_two_stamps(self):
        ns = self._functions()
        second = ns["format_metrics_ack"](dict(self.MESSAGE), 1250)
        self.assertEqual(len(second), 2)
        self.assertEqual(
            self._names(second),
            {"iot_sensor_vm_write_ack_ts", "iot_sensor_latency_ms"},
        )

    def test_payload_pass_is_complete(self):
        ns = self._functions()
        first = ns["format_metrics"](dict(self.MESSAGE), 1100)
        for field in ("ts", "pm1", "pm25", "pm10", "temp", "hum", "nats_exit_ts"):
            self.assertIn(f"iot_sensor_{field}", self._names(first))

    def test_latency_is_ack_minus_sensor(self):
        ns = self._functions()
        second = ns["format_metrics_ack"](dict(self.MESSAGE), 1250)
        self.assertIn('iot_sensor_latency_ms{device_id="d1"} 250', second)

    def test_render_respects_the_only_filter(self):
        ns = self._functions()
        out = ns["_render"](dict(self.MESSAGE), "d1", only=("ts",))
        self.assertEqual(out, ['iot_sensor_ts{device_id="d1"} 1000'])

    def test_render_skips_non_numeric_and_bool(self):
        ns = self._functions()
        data = {"device_id": "d", "ok": True, "name": "x", "n": None, "v": 1}
        out = ns["_render"](data, "d")
        self.assertEqual(out, ['iot_sensor_v{device_id="d"} 1'])


class TestMeasurementContract(unittest.TestCase):
    """The properties the paper's claims rest on, pinned against the real file."""

    def _fn(self, name, kind=ast.FunctionDef):
        tree = ast.parse(CONSUMER.read_text())
        return next(
            n for n in ast.walk(tree)
            if isinstance(n, kind) and n.name == name
        )

    def test_first_pass_omits_ack_fields(self):
        """Emitting the ack stamp in the payload request would stamp it before
        the write, making latency measure sensor -> write-start."""
        fn = self._fn("format_metrics")
        strings = {n.value for n in ast.walk(fn) if isinstance(n, ast.Constant)}
        self.assertNotIn("vm_write_ack_ts", strings)
        self.assertNotIn("latency_ms", strings)

    def test_second_pass_emits_ack_fields(self):
        fn = self._fn("format_metrics_ack")
        strings = {n.value for n in ast.walk(fn) if isinstance(n, ast.Constant)}
        self.assertIn("vm_write_ack_ts", strings)
        self.assertIn("latency_ms", strings)

    def test_ack_timestamp_follows_the_write(self):
        src = ast.unparse(self._fn("process_chunk", ast.AsyncFunctionDef))
        self.assertLess(
            src.index("session.post"),
            src.index("ack_ts = now_ms()"),
            "ack_ts is stamped before the POST it acknowledges",
        )

    def test_two_writes_per_chunk(self):
        src = ast.unparse(self._fn("process_chunk", ast.AsyncFunctionDef))
        self.assertEqual(src.count("session.post"), 2)

    def test_ack_after_write_not_on_enqueue(self):
        """Acking on enqueue loses a failed write permanently."""
        src = ast.unparse(self._fn("process_chunk", ast.AsyncFunctionDef))
        self.assertLess(src.index("session.post"), src.index("msg.ack()"))

    def test_stream_has_explicit_retention_limits(self):
        """Unlimited retention grows the store without bound on a 57 GB card."""
        src = CONSUMER.read_text()
        self.assertIn("STREAM_MAX_AGE_S", src)
        self.assertIn("STREAM_MAX_BYTES", src)
        fn = self._fn("setup", ast.AsyncFunctionDef)
        rendered = ast.unparse(fn)
        self.assertIn("max_age", rendered)
        self.assertIn("max_bytes", rendered)
        self.assertIn("update_stream", rendered)

    def test_pull_consumer_shared_durable(self):
        src = CONSUMER.read_text()
        self.assertIn("pull_subscribe", src)
        self.assertNotIn("js.subscribe(", src)


if __name__ == "__main__":
    unittest.main(verbosity=2)
