"""The readable consumer copy must match the ConfigMap that is actually deployed.

`manifests/nats-consumer/consumer.py` exists only so the script can be read and
diffed. `configmap.yaml` is what the Deployment mounts and what ArgoCD
reconciles, so the two drifting apart means the file people review is not the
code that runs.

This already happened once: the header of the copy documented a resync command
that redirected the ConfigMap key over the file, which destroyed the header
itself. A reader was then left with a plain script with no indication that it
was generated or where the real source was. The copy is now regenerated by
`make sync-consumer`, and these tests keep the marker, the header, and the
bodies honest.
"""

from __future__ import annotations

import ast
import importlib.util
import sys
import unittest
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
MANIFESTS = REPO / "manifests" / "nats-consumer"
sys.path.insert(0, str(REPO))

_spec = importlib.util.spec_from_file_location(
    "sync_consumer", MANIFESTS / "sync_consumer.py"
)
sync_consumer = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(sync_consumer)


class TestConfigmapIsSourceOfTruth(unittest.TestCase):
    def test_configmap_contains_the_script(self):
        data = yaml.safe_load((MANIFESTS / "configmap.yaml").read_text())
        self.assertIn("consumer.py", data["data"])

    def test_copy_matches_configmap(self):
        self.assertEqual(
            sync_consumer.current_copy(),
            sync_consumer.configmap_source().rstrip("\n") + "\n",
        )

    def test_check_mode_passes(self):
        import io
        from contextlib import redirect_stdout

        buf = io.StringIO()
        old_argv = sys.argv
        sys.argv = ["sync_consumer.py", "--check"]
        try:
            with redirect_stdout(buf):
                rc = sync_consumer.main()
        finally:
            sys.argv = old_argv
        self.assertEqual(rc, 0, buf.getvalue())
        self.assertIn("matches", buf.getvalue())

    def test_write_is_idempotent(self):
        """Re-syncing must not rewrite the file or duplicate the header."""
        before = (MANIFESTS / "consumer.py").read_text()
        self.assertFalse(sync_consumer.write_copy(sync_consumer.configmap_source()))
        after = (MANIFESTS / "consumer.py").read_text()
        self.assertEqual(before, after)
        self.assertEqual(after.count(sync_consumer.MARKER), 1)


class TestCopyHeaderSurvivesSync(unittest.TestCase):
    def test_header_present(self):
        text = (MANIFESTS / "consumer.py").read_text()
        self.assertTrue(text.startswith("#!/usr/bin/env python3"))
        self.assertIn("DO NOT EDIT THIS FILE TO CHANGE BEHAVIOUR", text)
        self.assertIn("configmap.yaml", text)

    def test_marker_is_unambiguous(self):
        """The marker must not be a prefix of itself.

        Splitting on a marker that also begins the marker's own line splits
        inside the header and reports a false mismatch. This bit once, when the
        marker was the shorter '# --- BEGIN GENERATED FROM configmap.yaml'.
        """
        body = sync_consumer.current_copy()
        self.assertNotIn("BEGIN GENERATED", body)
        # And the full marker is not a substring of the header that precedes it.
        header = (MANIFESTS / "consumer.py").read_text().split(
            sync_consumer.MARKER, 1
        )[0]
        self.assertNotIn(sync_consumer.MARKER, header)

    def test_embedded_source_is_valid_python(self):
        src = sync_consumer.configmap_source()


        ast.parse(src)


class TestConsumerParsesWithAckPass(unittest.TestCase):
    def test_format_metrics_omits_ack_fields(self):
        """Pass 1 must not emit an acknowledgement timestamp.

        Emitting it here would mean stamping it before the write it claims to
        acknowledge, which is the defect this split exists to prevent.

        The fields are checked as string constants because they are subscript
        keys (``data["latency_ms"]``), not identifiers.
        """
        tree = ast.parse(sync_consumer.configmap_source())
        fn = next(
            n
            for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and n.name == "format_metrics"
        )
        strings = {n.value for n in ast.walk(fn) if isinstance(n, ast.Constant)}
        self.assertNotIn("vm_write_ack_ts", strings)
        self.assertNotIn("latency_ms", strings)
        self.assertIn("nats_exit_ts", strings)

    def test_format_metrics_ack_emits_both_fields(self):
        tree = ast.parse(sync_consumer.configmap_source())
        fn = next(
            n
            for n in ast.walk(tree)
            if isinstance(n, ast.FunctionDef) and n.name == "format_metrics_ack"
        )
        strings = {n.value for n in ast.walk(fn) if isinstance(n, ast.Constant)}
        self.assertIn("vm_write_ack_ts", strings)
        self.assertIn("latency_ms", strings)

    def test_ack_timestamp_is_taken_after_the_post(self):
        """`ack_ts = now_ms()` must follow the POST, not precede it.

        The order inside process_chunk is the whole point: the value cannot
        exist until the write carrying the payload has returned.
        """
        tree = ast.parse(sync_consumer.configmap_source())
        fn = next(
            n
            for n in ast.walk(tree)
            if isinstance(n, ast.AsyncFunctionDef) and n.name == "process_chunk"
        )
        source = ast.unparse(fn)
        ack_at = source.index("ack_ts = now_ms()")
        post_at = source.index("session.post")
        self.assertLess(
            post_at,
            ack_at,
            "ack_ts is stamped before the POST; latency_ms would measure "
            "sensor -> write-start instead of sensor -> write-acknowledged",
        )

    def test_two_passes_both_post(self):
        tree = ast.parse(sync_consumer.configmap_source())
        fn = next(
            n
            for n in ast.walk(tree)
            if isinstance(n, ast.AsyncFunctionDef) and n.name == "process_chunk"
        )
        source = ast.unparse(fn)
        self.assertEqual(source.count("session.post"), 2)


if __name__ == "__main__":
    unittest.main(verbosity=2)
