apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-consumer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/Sam1rShaban1/k3s-iot-stack
    targetRevision: main
    path: manifests/nats-consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: nats-consumer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
