apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: emqx
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: emqx
  ports:
    - port: 4370
      name: erlang-dist
