apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: emqx
spec:
  type: NodePort
  selector:
    app: emqx
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
      nodePort: 31883
    - port: 8083
      targetPort: 8083
      name: mqtt-ws
    - port: 18083
      targetPort: 18083
      name: dashboard
