---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nats
  namespace: nats
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: emqx
  namespace: emqx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: benthos
  namespace: benthos
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: benthos
