apiVersion: v1
kind: Pod
metadata:
  name: nats-simple
  namespace: nats
spec:
  nodeName: raspberrypi
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: nats-simple
      image: nats:2.12.5-alpine
      command: ["/bin/sh", "-c"]
      args: ["nats-server -js -m 8222"]
      ports:
        - containerPort: 4222
          hostPort: 4222
          name: nats
        - containerPort: 8222
          hostPort: 8222
          name: monitoring
      resources:
        requests:
          cpu: "200m"
          memory: 100Mi
        limits:
          cpu: "500m"
          memory: 256Mi
