replicaCount: 2
service:
  type: LoadBalancer
  port: 1883

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  storageClass: longhorn-custom
