replicaCount: 2
service:
  type: ClusterIP   # Internal only

resources:
  requests:
    cpu: 400m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

persistence:
  enabled: true
  storageClass: longhorn-custom


JVM_HEAP_OPTS: "-Xms512m -Xmx768m"
