apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/namespaces
  - metallb
  - longhorn
  - emqx
  - benthos
  - nats
  - nats-consumer
  - victoriametrics
  - monitoring
  - loki
  - promtail
  - tempo
  - otel-collector

namespace: argocd
