apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/namespaces
  - longhorn/application.yaml
  - benthos/application.yaml
  - nats-consumer/application.yaml
