apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/namespaces
  - metallb/application.yaml
  - longhorn/application.yaml
  - nats/application.yaml
  - victoriametrics/application.yaml
  - monitoring/application.yaml
  - benthos/application.yaml
  - nats-consumer/application.yaml
