apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts
    targetRevision: 0.33.0
    chart: victoria-metrics-single
    helm:
      releaseName: victoriametrics
      valuesFiles:
        - ../../files/victoriametrics-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: victoriametrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
