#!/usr/bin/env python3
"""Readable copy of the deployed consumer.

DO NOT EDIT THIS FILE TO CHANGE BEHAVIOUR.
The source of truth is the `consumer.py` key in
manifests/nats-consumer/configmap.yaml, which is what the Deployment mounts
and ArgoCD reconciles. This copy exists for reading and diffing.

To resync after editing the ConfigMap:

    python3 -c "import yaml;open('consumer.py','w').write(yaml.safe_load(open('configmap.yaml'))['data']['consumer.py'])"
"""
# --- BEGIN GENERATED FROM configmap.yaml ---
#!/usr/bin/env python3
import asyncio
import json
import time
import os
import aiohttp
from nats.aio.client import Client as NATS
from nats.js.api import AckPolicy, ConsumerConfig

# nats-py 2.14 puts TimeoutError in nats.errors, not nats.js.errors, and
# has no EmptyError at all. Import defensively so a version change in the
# base image cannot crash the consumer at import time.
try:
    from nats.errors import TimeoutError as NatsTimeoutError
except ImportError:  # pragma: no cover
    NatsTimeoutError = asyncio.TimeoutError

NATS_URL = os.getenv("NATS_URL", "nats://nats.nats.svc.cluster.local:4222")
VM_URL = os.getenv(
    "VICTORIA_METRICS_URL",
    "http://victoriametrics-victoria-metrics-single-server."
    "victoriametrics.svc.cluster.local:8428/api/v1/import/prometheus",
)
STREAM = "IOT_DATA"
SUBJECT = "iot.data"
BATCH_SIZE = int(os.getenv("BATCH_SIZE", "5000"))
MAX_CONCURRENT_SENDS = int(os.getenv("MAX_CONCURRENT_SENDS", "32"))
WRITE_TIMEOUT_S = float(os.getenv("WRITE_TIMEOUT_S", "30"))
NAK_BACKOFF_S = float(os.getenv("NAK_BACKOFF_S", "1.0"))
NAK_BACKOFF_MAX_S = float(os.getenv("NAK_BACKOFF_MAX_S", "30.0"))
# Pull-consumer parameters. P0.6: the durable is shared by every replica so
# JetStream distributes batches between them.
DURABLE = os.getenv("CONSUMER_DURABLE", "metrics-consumer-pull")
FETCH_TIMEOUT_S = float(os.getenv("FETCH_TIMEOUT_S", "1.0"))
ACK_WAIT_S = float(os.getenv("ACK_WAIT_S", "60"))
MAX_ACK_PENDING = int(os.getenv("MAX_ACK_PENDING", "10000"))
# -1 == redeliver indefinitely, which is what paper section VII describes.
MAX_DELIVER = int(os.getenv("MAX_DELIVER", "-1"))

_nak_backoff = NAK_BACKOFF_S

def now_ms():
    return int(time.time() * 1000)

async def setup():
    nc = NATS()
    await nc.connect(NATS_URL)
    js = nc.jetstream()
    for i in range(10):
        try:
            await js.add_stream(name=STREAM, subjects=[SUBJECT])
            print("Stream: %s ready" % STREAM)
            break
        except Exception as e:
            print("Stream attempt %d failed: %s" % (i + 1, e))
            await asyncio.sleep(1)
    return nc, js

def format_metrics(data, nats_exit_ts, vm_write_ack_ts):
    """Render one message as a bounded set of Prometheus series.

    Every series is keyed on device_id alone. Nothing emitted here is
    unbounded -- that is the entire point of the paper's §VI-C fix.
    """
    device = data.get("device_id", "unknown")
    sensor_ts = data.get("ts")
    data["nats_exit_ts"] = nats_exit_ts
    data["vm_write_ack_ts"] = vm_write_ack_ts
    if "benthos_entry_ts" in data:
        data["benthos_to_nats_latency_ms"] = nats_exit_ts - data["benthos_entry_ts"]
    if sensor_ts is not None:
        data["latency_ms"] = vm_write_ack_ts - sensor_ts
    lines = []
    for k, v in data.items():
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            lines.append('iot_sensor_%s{device_id="%s"} %s' % (k, device, v))
    return lines

async def process_chunk(session, chunk):
    """Write one chunk and settle every message in it exactly once."""
    global _nak_backoff

    # Per-message NATS exit stamp, taken before the write.
    stamped = [(msg, data, now_ms()) for (msg, data) in chunk]

    body = "\n".join(
        line
        for _msg, data, exit_ts in stamped
        for line in format_metrics(data, exit_ts, now_ms())
    )

    ok = False
    try:
        async with session.post(
            VM_URL,
            data=body,
            timeout=aiohttp.ClientTimeout(total=WRITE_TIMEOUT_S),
        ) as resp:
            if resp.status in (200, 204):
                ok = True
            else:
                text = await resp.text()
                print("VM error: %s - %s" % (resp.status, text[:200]))
    except Exception as e:
        print("VM error: %s" % e)

    if ok:
        _nak_backoff = NAK_BACKOFF_S
    else:
        _nak_backoff = min(_nak_backoff * 2, NAK_BACKOFF_MAX_S)
        print(
            "write failed; nak batch of %d, backing off %.1fs"
            % (len(chunk), _nak_backoff)
        )
        await asyncio.sleep(_nak_backoff)

    for msg, _data in chunk:
        try:
            if ok:
                await msg.ack()
            else:
                await msg.nak()
        except Exception as e:
            print("settle failed: %s" % e)

async def batch_sender(session, batch_queue):
    """Single drain path. Polls the queue; chunks by BATCH_SIZE."""
    semaphore = asyncio.Semaphore(MAX_CONCURRENT_SENDS)

    async def guarded(chunk):
        async with semaphore:
            await process_chunk(session, chunk)

    while True:
        if not batch_queue:
            await asyncio.sleep(0.002)
            continue
        chunk = batch_queue[:BATCH_SIZE]
        del batch_queue[:BATCH_SIZE]
        await guarded(chunk)

async def main():
    print("Starting NATS consumer (pull mode, batch_size=%d)" % BATCH_SIZE)
    nc, js = await setup()

    # P0.6: this was a PUSH consumer (js.subscribe with a queue group).
    # A push consumer has exactly ONE bound subscription, so with replicas: 3
    # two of the three replicas block in subscribe() and never consume --
    # the pipeline silently scaled at 1x regardless of the replica count.
    # Symptoms seen during recovery: replicas stuck after "Subscribing to
    # iot.data", and JetStreamError "consumer is already bound to a
    # subscription" when a replica restarted.
    #
    # A PULL consumer lets every replica share the durable and have the
    # server distribute batches between them, which is the behaviour the
    # Deployment's replica count was always meant to provide.
    print("Creating pull subscription for %s (durable=%s)" % (SUBJECT, DURABLE))
    sub = await js.pull_subscribe(
        subject=SUBJECT,
        durable=DURABLE,
        stream=STREAM,
        config=ConsumerConfig(
            ack_policy=AckPolicy.EXPLICIT,
            max_deliver=MAX_DELIVER,
            # nats-py 2.14 takes ack_wait in SECONDS and multiplies by
            # 1e9 itself. Passing nanoseconds overflows to 6e19 and the
            # server rejects it; passing a timedelta fails in the client's
            # int() conversion. Verified empirically against 2.14.0.
            ack_wait=ACK_WAIT_S,
            max_ack_pending=MAX_ACK_PENDING,
        ),
    )

    batch_queue = []
    connector = aiohttp.TCPConnector(limit=200, limit_per_host=200)
    async with aiohttp.ClientSession(connector=connector) as session:
        sender = asyncio.create_task(batch_sender(session, batch_queue))
        try:
            fetches = 0
            while True:
                try:
                    msgs = await sub.fetch(
                        batch=BATCH_SIZE, timeout=FETCH_TIMEOUT_S
                    )
                    fetches += 1
                    if fetches % 20 == 1:
                        print("fetch ok: %d msgs (total fetches %d)"
                              % (len(msgs) if msgs else 0, fetches))
                except (asyncio.TimeoutError, NatsTimeoutError):
                    continue
                except Exception as e:
                    # P0.6: nats-py raises its own TimeoutError, not
                    # asyncio's, so a quiet pull loop previously looked
                    # identical to a healthy idle one. Report the type.
                    print("fetch error %s: %s" % (type(e).__name__, e))
                    await asyncio.sleep(1.0)
                    continue
                if not msgs:
                    continue
                for msg in msgs:
                    try:
                        batch_queue.append((msg, json.loads(msg.data.decode())))
                    except Exception as e:
                        print("Err: %s" % e)
                        try:
                            await msg.nak()
                        except Exception:
                            pass
        finally:
            sender.cancel()

asyncio.run(main())
