apiVersion: v1
kind: Pod
metadata:
  name: nats-consumer
  namespace: nats-consumer
spec:
  nodeName: raspberrypi
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  restartPolicy: Never
  containers:
    - name: nats-consumer
      image: docker.io/library/nats-consumer:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: NATS_URL
          value: "127.0.0.1:4222"
        - name: VICTORIA_METRICS_URL
          value: "http://192.168.1.50:30000/api/v1/import/prometheus"
        - name: BATCH_SIZE
          value: "500000"
        - name: FETCH_WORKERS
          value: "500"