#!/usr/bin/env python3
"""Regenerate the readable copy of the consumer from the ConfigMap.

`manifests/nats-consumer/configmap.yaml` is the source of truth: it is what the
Deployment mounts and what ArgoCD reconciles.
`manifests/nats-consumer/consumer.py` exists only so the script can be read and
diffed in a normal editor.

The header of that copy records where the real source is, so it must survive
the sync. Writing the ConfigMap key straight over the file -- which is what the
command previously documented in the header itself did -- destroys the header
and leaves a file that no longer says it is generated. That is how the copy
silently stopped being a copy.

Run via `make sync-consumer`. `make check-consumer` verifies the two agree.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
CONFIGMAP = HERE / "configmap.yaml"
COPY = HERE / "consumer.py"

HEADER = '''#!/usr/bin/env python3
"""Readable copy of the deployed consumer.

DO NOT EDIT THIS FILE TO CHANGE BEHAVIOUR.

The source of truth is the `consumer.py` key in
manifests/nats-consumer/configmap.yaml, which is what the Deployment mounts
and ArgoCD reconciles. This copy exists for reading and diffing.

To resync after editing the ConfigMap, run `make sync-consumer` from the
repository root. Do not redirect the ConfigMap key over this file: that
overwrites the header too, and the header is what tells the next reader
where the real source is.

A regression test asserts this file matches the ConfigMap, so drift fails the
test suite rather than being discovered during a benchmark run.
"""
MARKER
'''

MARKER = "# --- BEGIN GENERATED FROM configmap.yaml (via `make sync-consumer`) ---"


def configmap_source() -> str:
    data = yaml.safe_load(CONFIGMAP.read_text()) or {}
    scripts = data.get("data") or {}
    if "consumer.py" not in scripts:
        raise SystemExit(f"configmap has no data['consumer.py'] key: {CONFIGMAP}")
    return scripts["consumer.py"]


def current_copy() -> str:
    """The generated body currently in the copy, with the header removed."""
    if not COPY.exists():
        return ""
    text = COPY.read_text()
    if MARKER not in text:
        # No marker: either unsynced, or a hand-edited file. Return the whole
        # thing so the caller reports a difference rather than a false match.
        return text
    return text.split(MARKER, 1)[1].lstrip("\n")


def write_copy(source: str) -> bool:
    desired = source.rstrip("\n") + "\n"
    if COPY.exists() and current_copy() == desired:
        return False
    COPY.write_text(HEADER + desired)
    return True


def main() -> int:
    argv = sys.argv[1:]
    check = "--check" in argv

    source = configmap_source()
    if check:
        if current_copy() != source.rstrip("\n") + "\n":
            print(
                "consumer.py is out of sync with configmap.yaml.\n"
                "Run: make sync-consumer"
            )
            return 1
        print("consumer.py matches configmap.yaml")
        return 0

    changed = write_copy(source)
    print("consumer.py updated" if changed else "consumer.py already in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
