apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: benthos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://benthosdev.github.io/charts
    targetRevision: 0.6.0
    chart: benthos
    helm:
      releaseName: benthos
      valuesFiles:
        - ../../files/benthos-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: benthos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
