apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: benthos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://benthosdev.github.io/charts
    targetRevision: 0.6.0
    chart: benthos
    helm:
      releaseName: benthos
      parameters:
        - name: replicaCount
          value: "1"
        - name: persistence.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: benthos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
